spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.106.120.147:3306/sharehub?useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: root
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
  freemarker:
    suffix: .ftl
    settings:
      classic_compatible: true
  redis:
    database: 0
    port: 6379
    password:
    host: 47.106.120.147
wechat:
  jsAppId: wxe00253202c33f8a6
  jsAppSecret: ba77561ceaa4ef3edb4ccdf787d93d70
  token: 71895h1iuiyf89hio2yr98fhf3
server:
  domain: http://47.106.120.147:8080